# Generated by Django 5.1 on 2024-09-04 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='response',
            name='adverts_res_time_cr_d11293_idx',
        ),
        migrations.RemoveField(
            model_name='response',
            name='level',
        ),
        migrations.RemoveField(
            model_name='response',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='response',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='response',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='response',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=10, verbose_name='Статус отклика'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['-time_create', 'time_update', 'status'], name='adverts_res_time_cr_1866a0_idx'),
        ),
    ]
