# Generated by Django 5.0.7 on 2024-08-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_US',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text_en_US',
            field=models.TextField(default='Здесь пока нет текста.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text_ru',
            field=models.TextField(default='Здесь пока нет текста.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type_en_US',
            field=models.CharField(choices=[('ART', 'Статья'), ('NEW', 'Новость')], default='ART', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type_ru',
            field=models.CharField(choices=[('ART', 'Статья'), ('NEW', 'Новость')], default='ART', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_US',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(default='Здесь пока нет текста.'),
        ),
    ]
